
services:
  db:
    image: postgres:16
    container_name: mcp_pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: swanhtwn12@
      POSTGRES_DB: swandb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
